---
- name: Plugins | Set ohmyzsh plugins to used
  lineinfile:
    path: ~/.zshrc
    regexp: '^plugins='
    line: 'plugins=({{ ohmyzsh_plugins | join(" ") }})'
  become: true
  become_user: "{{ item }}"
  with_items: "{{ ohmyzsh_users }}"
