---
- name: Plugins | Set ohmyzsh plugins to used
  lineinfile:
    path: "{{ item['home'] }}/.zshrc"
    regexp: '^plugins='
    line: 'plugins=({{ ohmyzsh_plugins | join(" ") }})'
    owner: "{{ item['name'] }}"
    group: "{{ item['group'] }}"
  loop: "{{ ohmyzsh_users_information }}"
