---
- name: Setup | Package requirements
  package:
    name: "{{ package_requirements[ansible_facts['os_family']] | default(default_package_requirements) }}"
    state: present

- name: Setup | Download ohmyzsh
  git:
    repo: 'https://github.com/ohmyzsh/ohmyzsh.git'
    dest: ~/.oh-my-zsh
    depth: 1
    update: no
  become: true
  become_user: "{{ item }}"
  notify: Configure .zshrc
  with_items: "{{ ohmyzsh_users }}"

- name: Setup | Flush handler
  meta: flush_handlers

- name: Setup | Set zsh as default user shell
  ansible.builtin.user:
    name: "{{ ohmyzsh_users }}"
    shell: "{{ zsh_bin_path }}"
  become: true
  with_items: "{{ ohmyzsh_users }}"
