---
- name: Setup | Package requirements
  ansible.builtin.package:
    name: "{{ _package_requirements[ansible_facts['os_family']] | default(_default_package_requirements) }}"
    state: present
  become: "{{ ansible_facts['system'] != 'Darwin' }}"

- name: Get users information
  ansible.builtin.user:
    name: "{{ item }}"
    shell: "{{ _zsh_bin_path }}"
    state: present
  register: ohmyzsh_users_register
  loop: "{{ ohmyzsh_users }}"

- name: Extract only 'name', 'home' and 'group' fields from ohmyzsh_users_register variable
  ansible.builtin.set_fact:
    ohmyzsh_users_information: "{{ ohmyzsh_users_information | default([]) + [{'name': item['name'], 'home': item['home'], 'group': item['group']}] }}"
  no_log: true
  loop: "{{ ohmyzsh_users_register.results }}"

- name: Setup | Download ohmyzsh
  ansible.builtin.git:
    repo: '{{ ohmyzsh_repo_url }}'
    dest: "{{ item['home'] }}/.oh-my-zsh"
    depth: 1
    update: "{{ ohmyzsh_update }}"
  notify: Configure .zshrc
  loop: "{{ ohmyzsh_users_information }}"

- name: Setup user permission on Git repository
  ansible.builtin.file:
    path: "{{ item['home'] }}/.oh-my-zsh"
    owner: "{{ item['name'] }}"
    group: "{{ item['group'] }}"
    recurse: true
    state: directory
  loop: "{{ ohmyzsh_users_information }}"

- name: Setup | Flush handler
  ansible.builtin.meta: flush_handlers
