---
- name: Converge
  hosts: all
  become: yes
  tasks:
    - name: "Include ansible-role-ohmyzsh"
      include_role:
        name: "ansible-role-ohmyzsh"
      vars:
        ohmyzsh_users:
          - root
          - foo
          - bar
