---
- name: Prepare
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: OpenBSD | Install Ansible requirements
      ansible.builtin.raw: pkg_add -z python3 unzip-6

    - name: OpenBSD | Create test users
      ansible.builtin.user:
        name: "{{ item }}"
      loop:
        - foo
        - bar
