---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Verify | ohmyzsh folder shoud be present
      file:
        path: ~/.oh-my-zsh
      register: ohmyzsh_file

    - name: Verify | zsh shell should be use
      user:
        name: "{{ item }}"
        shell: /usr/bin/zsh
      register: ohmyzsh_shell
      loop:
        - root
        - foo
        - bar

    - name: Verify | ohmyzsh {{ ansible_env.ohmyzsh_theme }} theme should be present
      command: grep 'ZSH_THEME="{{ ansible_env.ohmyzsh_theme }}"' ~/.zshrc
      register: ohmyzsh_theme

    - name: Verify | ohmyzsh plugins should be present
      command: grep 'plugins=({{ ansible_env.ohmyzsh_plugins.split(",") | join(" ") }})' ~/.zshrc
      register: ohmyzsh_plugins

    - name: Verify | Verify commands outputs
      assert:
        that:
          - not ohmyzsh_file.changed
          - not ohmyzsh_shell.changed
          - ohmyzsh_theme.rc == 0
          - ohmyzsh_plugins.rc == 0
        success_msg: "All tests passed"
