---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-role-ohmyzsh"
      include_role:
        name: "ansible-role-ohmyzsh"
      vars:
        ohmyzsh_theme: "{{ ansible_env.ohmyzsh_theme }}"
        ohmyzsh_plugins: "{{ ansible_env.ohmyzsh_plugins.split(',') }}"
