---
- name: Converge
  hosts: all
  become: true
  roles:
    - role: diodonfrost.ohmyzsh
      vars:
        ohmyzsh_theme: "{{ lookup('env', 'ohmyzsh_theme') | default('robbyrussell', True) }}"
        ohmyzsh_plugins: "{{ lookup('env', 'ohmyzsh_plugins') | default(['git', 'ansible'], True) }}"
        ohmyzsh_users:
          - root
          - foo
          - bar
