---
- name: Prepare
  hosts: all
  become: yes
  tasks:
    - name: FreeBSD | Install Ansible requirements
      community.general.pkgng:
        name: gtar
        state: present

    - name: FreeBSD | Create test users
      ansible.builtin.user:
        name: "{{ item }}"
      loop:
        - foo
        - bar
